language: go

matrix:
  include:
    - go: 1.12.x
    - go: 1.13.x
env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

script:
  - go get -v ./...
  - go get github.com/modocache/gover
  - go test -coverprofile=h2lb.coverprofile
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci

notifications:
  email:
    on_success: never